
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Clean up the URL if it has duplicates
const cleanUrl = (url: string) => {
  if (url && url.includes('https://') && url.lastIndexOf('https://') > 0) {
    return url.substring(url.lastIndexOf('https://'));
  }
  return url;
};

const SUPABASE_URL = cleanUrl(import.meta.env.VITE_SUPABASE_URL) || "https://tzdlzlqowxhosudqyuho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6ZGx6bHFvd3hob3N1ZHF5dWhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3Mjg0MDcsImV4cCI6MjA1NjMwNDQwN30.W4dtmF8xR6wD2KI3YrDNsu_orVUMiIJFL1wo4JSSV0k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
