
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Clean up the URL if it has duplicates
const cleanUrl = (url: string) => {
  if (url && url.includes('https://') && url.lastIndexOf('https://') > 0) {
    return url.substring(url.lastIndexOf('https://'));
  }
  return url;
};

const SUPABASE_URL = cleanUrl(import.meta.env.VITE_SUPABASE_URL) ;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

console.log('SUPABASE_URL:', SUPABASE_URL);
console.log('SUPABASE_PUBLISHABLE_KEY:', SUPABASE_PUBLISHABLE_KEY);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
